INSERT INTO doctor (`name`, `practiceName`) VALUES
	('Sonja Lahmers, M.D.', 'Arizona Advanced Dermatology'),
	('Pamula Marshall, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Argentina Mungo, M.D.', 'St John's Clinic'),
	('Tamisha Georgeson, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Clint Imburgia, M.D.', 'Sanford Women's Health Plaza'),
	('Tiera Whitlock, M.D.', 'Northwest Occupational Medicine'),
	('Billie Poser, M.D.', 'Bainbridge Pediatrics'),
	('Lyn Brigham, M.D.', 'Center For Genetic Testing At Saint'),
	('Noelia Ledon, M.D.', 'Panhandle Plastic Surgery'),
	('Vivian Finkelstein, M.D.', 'University Orthopedics Ctr'),
	('Pearlie Mcelhany, M.D.', 'Trusstek'),
	('Merlene Humeniuk, M.D.', 'Southcenter Cosmetic Surgery'),
	('Apryl Dunigan, M.D.', 'Nova Care'),
	('Marcellus Schwendemann, M.D.', 'Temas Eye Ctr'),
	('Eleanor Vegter, M.D.', 'Southwest Dermatology'),
	('Kazuko Bellisle, M.D.', 'Sanford Women's Health Plaza'),
	('Kimberlie Scarsdale, M.D.', 'St Louis Gynecology & Oncology'),
	('Donita Cabe, M.D.', 'Charles C Young MD'),
	('Charla Joesph, M.D.', 'Moss Bay Wellness Center'),
	('Sandy Mckeel, M.D.', 'Orthopedics Northwest Llp'),
	('Bok Harrel, M.D.', 'Womans Digital Imaging'),
	('Jason Mcniell, M.D.', 'Refractive Center Of Ohio'),
	('Angelia Blocker, M.D.', 'Allergy & Asthma Care'),
	('Dylan Esplain, M.D.', 'Cook Children's Genetic Svc'),
	('Karon Knittel, M.D.', 'Fisher Investment Corporation'),
	('Odessa Kirn, M.D.', 'St Louis Gynecology & Oncology'),
	('Barney Durate, M.D.', 'Moss Bay Wellness Center'),
	('Leontine Horka, M.D.', 'Northwest Occupational Medicine'),
	('Selena Delson, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Simone Metzgar, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Elfreda Schachterle, M.D.', 'Womans Digital Imaging'),
	('Forest Hillary, M.D.', 'Allergy Sleep & Lung Care'),
	('Rina Beja, M.D.', 'Allergy Sleep & Lung Care'),
	('Elfriede Nerby, M.D.', 'Refractive Center Of Ohio'),
	('Candi Greyovich, M.D.', 'New Horizons'),
	('Angle Distler, M.D.', 'Charles C Young MD'),
	('Prince Spadafora, M.D.', 'Heaton Williams & Benavides'),
	('Lindsay Canizales, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Magdalene Neidecker, M.D.', 'Silverdale Psychiatric'),
	('Veronica Stillions, M.D.', 'Allergy Sleep & Lung Care'),
	('Rochell Mccord, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Raye Kainz, M.D.', 'Advantage Health Care'),
	('Taina Allende, M.D.', 'F P Assoc'),
	('Toby Gibby, M.D.', 'Memorial NW Otolaryngology'),
	('Shavon Linman, M.D.', 'Anoka Aeromedical Clinic'),
	('Jessenia Shi, M.D.', 'Refractive Center Of Ohio'),
	('Brandee Fullagar, M.D.', 'Wattles Park Family Practice'),
	('Saundra Azhocar, M.D.', 'St Louis Gynecology & Oncology'),
	('Roxanne Schiver, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Slyvia Hulett, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Mariella Bakowski, M.D.', 'South Valley Inc'),
	('Sharell Ayre, M.D.', 'Bainbridge Pediatrics'),
	('Margarita Maranda, M.D.', 'Panhandle Plastic Surgery'),
	('Vertie Placha, M.D.', 'North Star Medical Center'),
	('Carline Carmany, M.D.', 'Center For Sight Inc'),
	('Wilmer Kalenak, M.D.', 'Charles C Young MD'),
	('Erma Parido, M.D.', 'St Louis Gynecology & Oncology'),
	('Tamela Tyree, M.D.', 'Silverdale Psychiatric'),
	('Teddy Sjodin, M.D.', 'Cascade Physicians'),
	('Denita Yauch, M.D.', 'St Josephs Hospital And Med Center'),
	('Carolina Nagengast, M.D.', 'Fusion Therapy LLC'),
	('Noel Taccetta, M.D.', 'Advantage Health Care'),
	('Cecelia Chacko, M.D.', 'Heaton Williams & Benavides'),
	('Tillie Ausburn, M.D.', 'Temas Eye Ctr'),
	('Travis Deluna, M.D.', 'Orthopedics Northwest Llp'),
	('Jayme Widjaja, M.D.', 'Pediatric Place'),
	('Sharilyn Facello, M.D.', 'Associated Colon & Rectal Srgn'),
	('Alica Omlin, M.D.', 'Wattles Park Family Practice'),
	('Nancey Tesar, M.D.', 'South Valley Inc'),
	('Woodrow Mccomis, M.D.', 'Advantage Health Care'),
	('Vonnie Joachim, M.D.', 'Wattles Park Family Practice'),
	('Akilah Avola, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Bryce Hottman, M.D.', 'Fusion Therapy LLC'),
	('Suanne Rodges, M.D.', 'North Star Medical Center'),
	('Keitha Juart, M.D.', 'South Valley Inc'),
	('Van Benckendorf, M.D.', 'Silverdale Psychiatric'),
	('Tish Mcnespey, M.D.', 'Arizona Advanced Dermatology'),
	('Travis Vigneau, M.D.', 'Orthopedics Northwest Llp'),
	('Cordell Fehl, M.D.', 'Trusstek'),
	('Haydee Koritko, M.D.', 'Sanford Women's Health Plaza'),
	('Jennifer Perine, M.D.', 'Heaton Williams & Benavides'),
	('Jerry Carrus, M.D.', 'Silverdale Psychiatric'),
	('James Mcquilliams, M.D.', 'Heaton Williams & Benavides'),
	('Neda Wray, M.D.', 'Silverdale Psychiatric'),
	('Addie Ludemann, M.D.', 'St Josephs Hospital And Med Center'),
	('Gregoria Hubbartt, M.D.', 'Fisher Investment Corporation'),
	('Lizzette Seanger, M.D.', 'University Orthopedics Ctr'),
	('Bianca Cosenza, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Herman Lewandowski, M.D.', 'New Horizons'),
	('Mickey Harnois, M.D.', 'Healthfirst Sleep Center'),
	('Kasi Kilborn, M.D.', 'Memorial NW Otolaryngology'),
	('Alphonse Furth, M.D.', 'Pediatric Place'),
	('Ghislaine Sosh, M.D.', 'Northwest Occupational Medicine'),
	('Shantel Vonbraunsberg, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Amberly Soos, M.D.', 'Temas Eye Ctr'),
	('Angelyn Starling, M.D.', 'St Louis Gynecology & Oncology'),
	('Yan Rocheleau, M.D.', 'Center For Psychotherapy'),
	('Florence Augspurger, M.D.', 'Trusstek'),
	('Oralia Parsh, M.D.', 'Allergy & Asthma Care'),
	('Evette Mcdoniel, M.D.', 'Temas Eye Ctr'),
	('Renee Scarlet, M.D.', 'New Horizons'),
	('Margarito Berver, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Birgit Wengerd, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Nga Carpinelli, M.D.', 'F P Assoc'),
	('Oswaldo Lapidus, M.D.', 'St John's Clinic'),
	('King Haacke, M.D.', 'North Star Medical Center'),
	('Ervin Yellen, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Sonya Conti, M.D.', 'Charles C Young MD'),
	('Bobby Belch, M.D.', 'Associated Colon & Rectal Srgn'),
	('Roberto Maciejko, M.D.', 'South Valley Inc'),
	('Sylvie Vandaele, M.D.', 'Nova Care'),
	('Karolyn Rybinski, M.D.', 'Bainbridge Pediatrics'),
	('Aimee Hermus, M.D.', 'Heaton Williams & Benavides'),
	('Mark Minogue, M.D.', 'St Josephs Hospital And Med Center'),
	('Luanne Hendricks, M.D.', 'Advantage Health Care'),
	('Garnet Mckernin, M.D.', 'Moss Bay Wellness Center'),
	('Myriam Bevell, M.D.', 'Bainbridge Pediatrics'),
	('Yuriko Moose, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Dreama Urbas, M.D.', 'Memorial NW Otolaryngology'),
	('Raymundo Wartchow, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Wynell Megeath, M.D.', 'Northwest Occupational Medicine'),
	('Patrick Kissi, M.D.', 'Orthopedics Northwest Llp'),
	('Louann Watrs, M.D.', 'Womans Digital Imaging'),
	('Sadye Crouthamel, M.D.', 'Nova Care'),
	('Yuri Chappa, M.D.', 'Associated Colon & Rectal Srgn'),
	('Grant Tall, M.D.', 'Heaton Williams & Benavides'),
	('Wendell Angileri, M.D.', 'Fusion Therapy LLC'),
	('Vivan Medell, M.D.', 'Wattles Park Family Practice'),
	('Chanell Kvek, M.D.', 'Advantage Health Care'),
	('Zula Cortina, M.D.', 'Advantage Health Care'),
	('Enda Kanoff, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Jaquelyn Highsmith, M.D.', 'Healthfirst Sleep Center'),
	('Otha Waugaman, M.D.', 'Southwest Dermatology'),
	('Chong Campellone, M.D.', 'Panhandle Plastic Surgery'),
	('Kristina Klice, M.D.', 'Silverdale Psychiatric'),
	('Patti Caire, M.D.', 'Center For Psychotherapy'),
	('Oren Chitrik, M.D.', 'North Raleigh Pediatric Group'),
	('Michaele Dougharty, M.D.', 'Pediatric Place'),
	('Meagan Munafo, M.D.', 'University Orthopedics Ctr'),
	('Lorine Frishkorn, M.D.', 'Fisher Investment Corporation'),
	('Georgia Mix, M.D.', 'Silverdale Psychiatric'),
	('Jennine Vazguez, M.D.', 'Southwest Dermatology'),
	('Idell Grube, M.D.', 'North Raleigh Pediatric Group'),
	('Thi Pezzullo, M.D.', 'Bainbridge Pediatrics'),
	('Virginia Boldery, M.D.', 'St John's Clinic'),
	('Jani Spena, M.D.', 'Pediatric Place'),
	('Dominga Temple, M.D.', 'New Horizons'),
	('Mora Cantadore, M.D.', 'Temas Eye Ctr'),
	('Tarah Litmanowicz, M.D.', 'Cook Children's Genetic Svc'),
	('Babara Schalow, M.D.', 'Fisher Investment Corporation'),
	('Noemi Klingler, M.D.', 'Associated Colon & Rectal Srgn'),
	('Gladys Loach, M.D.', 'Center For Genetic Testing At Saint'),
	('Rebeca Derosie, M.D.', 'Sanford Women's Health Plaza'),
	('Shante Reiser, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Valene Shasky, M.D.', 'St Josephs Hospital And Med Center'),
	('Jessie Calowell, M.D.', 'Wattles Park Family Practice'),
	('Glenn Polintan, M.D.', 'Bainbridge Pediatrics'),
	('Jamee Zonker, M.D.', 'Silverdale Psychiatric'),
	('Karol Zellman, M.D.', 'Heaton Williams & Benavides'),
	('Nguyet Liquet, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Georgine Rutiaga, M.D.', 'North Raleigh Pediatric Group'),
	('Shandi Izak, M.D.', 'Pediatric Place'),
	('Terisa Hite, M.D.', 'Fisher Investment Corporation'),
	('Mireille Vore, M.D.', 'Southwest Dermatology'),
	('Jae Laro, M.D.', 'Center For Health & Wellness'),
	('Cori Sterpka, M.D.', 'Associated Colon & Rectal Srgn'),
	('Louie Prye, M.D.', 'St Josephs Hospital And Med Center'),
	('Claribel Penepent, M.D.', 'St Louis Gynecology & Oncology'),
	('Myrta Argudo, M.D.', 'Advantage Health Care'),
	('Karole Triska, M.D.', 'Healthfirst Sleep Center'),
	('Zola Arbizo, M.D.', 'Southwest Dermatology'),
	('Lavona Pinsoneault, M.D.', 'Allergy & Asthma Care'),
	('Cassy Killins, M.D.', 'Randolph Internal Medicine'),
	('Chrissy Forcino, M.D.', 'Allergy Sleep & Lung Care'),
	('Frank Haldeman, M.D.', 'Center For Health & Wellness'),
	('Jesse Farthing, M.D.', 'South Valley Inc'),
	('Elaine Valin, M.D.', 'St Josephs Hospital And Med Center'),
	('Coral Staubs, M.D.', 'Healthfirst Sleep Center'),
	('Leticia Crossland, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Sheree Kunsman, M.D.', 'Advantage Health Care'),
	('Darlena Aldredge, M.D.', 'Cook Children's Genetic Svc'),
	('Maya Kummer, M.D.', 'Nova Care'),
	('Cythia Ryhal, M.D.', 'St John's Clinic'),
	('Tiera Tangerman, M.D.', 'Cook Children's Genetic Svc'),
	('Kia Puc, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Carma Alfieri, M.D.', 'Advantage Health Care'),
	('Sheryll Wrobliski, M.D.', 'Center For Health & Wellness'),
	('Cathern Comas, M.D.', 'Southcenter Cosmetic Surgery'),
	('India Alderman, M.D.', 'F P Assoc'),
	('Brian Feela, M.D.', 'Womans Digital Imaging'),
	('Chang Pardee, M.D.', 'Bainbridge Pediatrics'),
	('Lieselotte Tuite, M.D.', 'Wattles Park Family Practice'),
	('Kit Bisker, M.D.', 'Center For Genetic Testing At Saint'),
	('Lesley Michals, M.D.', 'Arizona Advanced Dermatology'),
	('Dallas Tate, M.D.', 'Heaton Williams & Benavides'),
	('Aleisha Stroede, M.D.', 'St John's Clinic'),
	('Yan Ibara, M.D.', 'Allergy & Asthma Care'),
	('Mari Bonneau, M.D.', 'Advantage Health Care'),
	('Ivonne Leidel, M.D.', 'University Orthopedics Ctr'),
	('Kenia Frullate, M.D.', 'Cook Children's Genetic Svc'),
	('Flavia Baldassare, M.D.', 'Orthopedics Northwest Llp'),
	('Vincenza Helms, M.D.', 'Moss Bay Wellness Center'),
	('Wm Savells, M.D.', 'South Valley Inc'),
	('Claude Kook, M.D.', 'Refractive Center Of Ohio'),
	('Shawna Wilm, M.D.', 'Refractive Center Of Ohio'),
	('Alyson Grismore, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Tangela Frisinger, M.D.', 'Fusion Therapy LLC'),
	('Sung Paquin, M.D.', 'Moss Bay Wellness Center'),
	('Despina Patsy, M.D.', 'Charles C Young MD'),
	('Sean Masello, M.D.', 'Healthfirst Sleep Center'),
	('Faye Swainston, M.D.', 'Heaton Williams & Benavides'),
	('Valentine Imbier, M.D.', 'Pediatric Place'),
	('Carrol Beichner, M.D.', 'St Josephs Hospital And Med Center'),
	('Jospeh Lory, M.D.', 'Bainbridge Pediatrics'),
	('Ronald Claridge, M.D.', 'University Orthopedics Ctr'),
	('Leontine Benauides, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Shelton Gimbel, M.D.', 'Pediatric Place'),
	('Millicent Senior, M.D.', 'St Josephs Hospital And Med Center'),
	('Shalanda Onley, M.D.', 'North Star Medical Center'),
	('Danita Litty, M.D.', 'Healthfirst Sleep Center'),
	('Charles Bellomo, M.D.', 'Bainbridge Pediatrics'),
	('Rosalba Hollo, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Mira Kesich, M.D.', 'Charles C Young MD'),
	('Jenna Velez, M.D.', 'Associated Colon & Rectal Srgn'),
	('Lanny Annonio, M.D.', 'St John's Clinic'),
	('Aurea Sirek, M.D.', 'Silverdale Psychiatric'),
	('Sirena Angerman, M.D.', 'Cook Children's Genetic Svc'),
	('Georgeanna Dorsch, M.D.', 'St John's Clinic'),
	('Bobbie Indermuehle, M.D.', 'University Orthopedics Ctr'),
	('Shoshana Fuerte, M.D.', 'St Josephs Hospital And Med Center'),
	('Kennith Cezil, M.D.', 'Nova Care'),
	('Lucinda Schmig, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Librada Facio, M.D.', 'New Horizons'),
	('Bonny Arps, M.D.', 'Refractive Center Of Ohio'),
	('Owen Siedlik, M.D.', 'Arizona Advanced Dermatology'),
	('Jefferey Goettel, M.D.', 'Fisher Investment Corporation'),
	('Burton Virag, M.D.', 'Moss Bay Wellness Center'),
	('Darius Tenofsky, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Shawnna Cedano, M.D.', 'Nova Care'),
	('Guillermina Bezio, M.D.', 'North Star Medical Center'),
	('Teri Camastro, M.D.', 'Fusion Therapy LLC'),
	('Norbert Fant, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Lazaro Odorizzi, M.D.', 'Nova Care'),
	('Mabel Norfolk, M.D.', 'Sanford Women's Health Plaza'),
	('Elias Felker, M.D.', 'South Valley Inc'),
	('Belia Winner, M.D.', 'Center For Health & Wellness'),
	('Daine Noury, M.D.', 'Refractive Center Of Ohio'),
	('Lisbeth Walentoski, M.D.', 'Southwest Dermatology'),
	('Myrle Breitkreutz, M.D.', 'Healthfirst Sleep Center'),
	('Benedict Sotiriou, M.D.', 'Center For Genetic Testing At Saint'),
	('Elenora Plock, M.D.', 'Randolph Internal Medicine'),
	('Lakesha Freedland, M.D.', 'South Valley Inc'),
	('Giovanni Mcvean, M.D.', 'Southcenter Cosmetic Surgery'),
	('Donn Xiang, M.D.', 'Nova Care'),
	('Eddie Keaney, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Signe Dodgson, M.D.', 'Advantage Health Care'),
	('Ligia Huron, M.D.', 'St Louis Gynecology & Oncology'),
	('Elene Armacost, M.D.', 'New Horizons'),
	('Ines Brozowski, M.D.', 'Fisher Investment Corporation'),
	('Tegan Thoroughman, M.D.', 'University Orthopedics Ctr'),
	('Kym Domer, M.D.', 'Center For Genetic Testing At Saint'),
	('Ivelisse Furlotte, M.D.', 'Heaton Williams & Benavides'),
	('Gita Malanado, M.D.', 'South Valley Inc'),
	('Coralie Morgner, M.D.', 'Allergy & Asthma Care'),
	('Sau Zertuche, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Sau Cumberbatch, M.D.', 'Arizona Advanced Dermatology'),
	('Carlton Knop, M.D.', 'Southwest Dermatology'),
	('Hyo Server, M.D.', 'Refractive Center Of Ohio'),
	('Lorina Bergeron, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Windy Everson, M.D.', 'Randolph Internal Medicine'),
	('Criselda Carriedo, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Sommer Larroque, M.D.', 'Wattles Park Family Practice'),
	('Stephane Gouldie, M.D.', 'Panhandle Plastic Surgery'),
	('Adrian Houtman, M.D.', 'Trusstek'),
	('Roy Williemae, M.D.', 'Trusstek'),
	('Terrance Rudisell, M.D.', 'St John's Clinic'),
	('Kandice Valot, M.D.', 'Center For Genetic Testing At Saint'),
	('Rebbecca Riso, M.D.', 'New Horizons'),
	('Terrell Lusardi, M.D.', 'Sanford Women's Health Plaza'),
	('Reba Burghart, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Melita Adwell, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Sherise Provost, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Toccara Hafley, M.D.', 'Anoka Aeromedical Clinic'),
	('Marshall Lyng, M.D.', 'Memorial NW Otolaryngology'),
	('Martha Kokoska, M.D.', 'Fusion Therapy LLC'),
	('Manuela Abbate, M.D.', 'Associated Colon & Rectal Srgn'),
	('Maryrose Surman, M.D.', 'Randolph Internal Medicine'),
	('Trula Santiesteban, M.D.', 'Center For Genetic Testing At Saint'),
	('Cari Metevelis, M.D.', 'Womans Digital Imaging'),
	('Marge Gerberich, M.D.', 'Charles C Young MD'),
	('Hershel Molleda, M.D.', 'St Josephs Hospital And Med Center'),
	('Ruby Agricola, M.D.', 'Allergy Sleep & Lung Care'),
	('Randy Lucarell, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Sheri Thibodaux, M.D.', 'Panhandle Plastic Surgery'),
	('Jolie Sarwar, M.D.', 'Orthopedics Northwest Llp'),
	('Fiona Wlodarczyk, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Isabelle Nievas, M.D.', 'Silverdale Psychiatric'),
	('Latrina Mohn, M.D.', 'University Orthopedics Ctr'),
	('Chong Salb, M.D.', 'Memorial NW Otolaryngology'),
	('Kari Bagan, M.D.', 'Associated Colon & Rectal Srgn'),
	('Ralph Girone, M.D.', 'St Josephs Hospital And Med Center'),
	('Eufemia Figueredo, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Paz Paige, M.D.', 'Healthfirst Sleep Center'),
	('Philip Bradby, M.D.', 'St John's Clinic'),
	('Gerald Korey, M.D.', 'University Orthopedics Ctr'),
	('Virgina Coffey, M.D.', 'University Orthopedics Ctr'),
	('Josephina Dense, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Veronica Mentgen, M.D.', 'Refractive Center Of Ohio'),
	('Aleisha Laverne, M.D.', 'Heaton Williams & Benavides'),
	('Sha Sumaran, M.D.', 'Healthfirst Sleep Center'),
	('Bud Depner, M.D.', 'Memorial NW Otolaryngology'),
	('Vickey Guilliams, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Dakota Heitman, M.D.', 'Center For Genetic Testing At Saint'),
	('Katherin Niverson, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Jeannette Zicherman, M.D.', 'Bainbridge Pediatrics'),
	('Enda Hamill, M.D.', 'Sanford Women's Health Plaza'),
	('Dayna Cante, M.D.', 'Refractive Center Of Ohio'),
	('Latashia Ventresca, M.D.', 'Randolph Internal Medicine'),
	('Patrica Speelman, M.D.', 'St John's Clinic'),
	('Shiloh Lafaso, M.D.', 'Center For Health & Wellness'),
	('Karisa Pires, M.D.', 'Center For Psychotherapy'),
	('Scarlett Brindley, M.D.', 'Southwest Dermatology'),
	('Hosea Kita, M.D.', 'Anoka Aeromedical Clinic'),
	('Cecil Rinke, M.D.', 'New Horizons'),
	('Torie Gallante, M.D.', 'Advantage Health Care'),
	('Jestine Centanni, M.D.', 'St Louis Gynecology & Oncology'),
	('Summer Dantoni, M.D.', 'Nova Care'),
	('Rebbeca Opara, M.D.', 'Memorial NW Otolaryngology'),
	('Millard Isadore, M.D.', 'Center For Psychotherapy'),
	('Tu Placencio, M.D.', 'Panhandle Plastic Surgery'),
	('Gertie Flinders, M.D.', 'Womans Digital Imaging'),
	('Fran Mangano, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Jessica Manspeaker, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Gudrun Warfield, M.D.', 'F P Assoc'),
	('Colton Smail, M.D.', 'Randolph Internal Medicine'),
	('Rosena Gilmartin, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Noemi Kemplin, M.D.', 'Southwest Dermatology'),
	('Sergio Langwith, M.D.', 'Cook Children's Genetic Svc'),
	('Karlyn Haghighi, M.D.', 'Northwest Occupational Medicine'),
	('Kizzy Earles, M.D.', 'Southwest Dermatology'),
	('Rosana Rupard, M.D.', 'Anoka Aeromedical Clinic'),
	('Ethan Levett, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Madie Shorrock, M.D.', 'St John's Clinic'),
	('Effie Macura, M.D.', 'Fusion Therapy LLC'),
	('Jenine Kooker, M.D.', 'Nova Care'),
	('Na Jaurigui, M.D.', 'St John's Clinic'),
	('Thanh Rehmert, M.D.', 'Allergy Sleep & Lung Care'),
	('Valrie Taulbee, M.D.', 'Heaton Williams & Benavides'),
	('Tamera Klez, M.D.', 'Pediatric Place'),
	('Hilton Plumadore, M.D.', 'Temas Eye Ctr'),
	('Williemae Mayhorn, M.D.', 'Refractive Center Of Ohio'),
	('Shelli Shell, M.D.', 'North Raleigh Pediatric Group'),
	('Stephan Salway, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Margot Dewater, M.D.', 'Fisher Investment Corporation'),
	('Cherelle Mcgarvie, M.D.', 'Allergy & Asthma Care'),
	('Sachiko Levendosky, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Alexandra Barter, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Yolando Khounthavong, M.D.', 'Cook Children's Genetic Svc'),
	('Melissia Feisthamel, M.D.', 'Center For Psychotherapy'),
	('Franklyn Pavlosky, M.D.', 'University Orthopedics Ctr'),
	('Hue Riggsbee, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Sarita Gemberling, M.D.', 'New Horizons'),
	('Isabelle Reimann, M.D.', 'Southwest Dermatology'),
	('Darlene Garibay, M.D.', 'Fisher Investment Corporation'),
	('Edgardo Laverne, M.D.', 'St John's Clinic'),
	('Agustin Yochim, M.D.', 'Fusion Therapy LLC'),
	('Rory Lafoy, M.D.', 'New Horizons'),
	('Tera Briseno, M.D.', 'Allergy & Asthma Care'),
	('Dorla Coggin, M.D.', 'Center For Health & Wellness'),
	('Linh Keomanivong, M.D.', 'Orthopedics Northwest Llp'),
	('Mora Durke, M.D.', 'Womans Digital Imaging'),
	('Petrina Lesesne, M.D.', 'Trusstek'),
	('Shizue Bonomi, M.D.', 'St Josephs Hospital And Med Center'),
	('Fletcher Hilby, M.D.', 'Cook Children's Genetic Svc'),
	('Lynetta Sierer, M.D.', 'North Star Medical Center'),
	('Lizeth Crieghton, M.D.', 'Womans Digital Imaging'),
	('Sanora Schnieders, M.D.', 'Cascade Physicians'),
	('Meta Conveniencia, M.D.', 'Nova Care'),
	('Meryl Helt, M.D.', 'Center For Sight Inc'),
	('Felicia Guo, M.D.', 'Refractive Center Of Ohio'),
	('Elidia Lemear, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Keena Faria, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Dodie Cilfone, M.D.', 'Associated Colon & Rectal Srgn'),
	('Sabra Furlone, M.D.', 'Silverdale Psychiatric'),
	('Margie Stano, M.D.', 'Pediatric Place'),
	('Shirley Acedo, M.D.', 'Pediatric Place'),
	('Julian Maikoksoong, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Marilyn Mathre, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Theresa Suro, M.D.', 'Center For Sight Inc'),
	('Nu Raderstorf, M.D.', 'Memorial NW Otolaryngology'),
	('Ebony Barts, M.D.', 'Allergy & Asthma Care'),
	('Naida Jeronimo, M.D.', 'Heaton Williams & Benavides'),
	('Marshall Wims, M.D.', 'Silverdale Psychiatric'),
	('Nelson Krukowski, M.D.', 'Cascade Physicians'),
	('Belle Antinarelli, M.D.', 'South Valley Inc'),
	('Vicenta Smigiel, M.D.', 'University Orthopedics Ctr'),
	('Rebeca Ahia, M.D.', 'Charles C Young MD'),
	('Elana Callez, M.D.', 'Refractive Center Of Ohio'),
	('Farah Lagreca, M.D.', 'F P Assoc'),
	('Cruz Zammetti, M.D.', 'Hague Ctr-Cosmetic & Plastic'),
	('Kaylene Gilliam, M.D.', 'Bainbridge Pediatrics'),
	('Stephen Hunstiger, M.D.', 'Refractive Center Of Ohio'),
	('Luisa Dehay, M.D.', 'Pediatric Place'),
	('Leisha Hethcote, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Julianne Broward, M.D.', 'Center For Genetic Testing At Saint'),
	('Isela Nesland, M.D.', 'Cascade Physicians'),
	('Rosamaria Cerino, M.D.', 'Charles C Young MD'),
	('Ronny Rahm, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Merlin Adalja, M.D.', 'Center For Health & Wellness'),
	('Melia Paulsen, M.D.', 'Cook Children's Genetic Svc'),
	('Sherly Hubley, M.D.', 'Temas Eye Ctr'),
	('Krishna Elledge, M.D.', 'Trusstek'),
	('Alisa Eyton, M.D.', 'Cook Children's Genetic Svc'),
	('Mora Cumoletti, M.D.', 'South Valley Inc'),
	('Leatha Kacher, M.D.', 'Memorial NW Otolaryngology'),
	('Anamaria Strande, M.D.', 'Temas Eye Ctr'),
	('Candra Karpinsky, M.D.', 'Trusstek'),
	('Romana Gacia, M.D.', 'Anoka Aeromedical Clinic'),
	('Isobel Loze, M.D.', 'Center For Genetic Testing At Saint'),
	('Lisa Grano, M.D.', 'Orthopedics Northwest Llp'),
	('Clark Standors, M.D.', 'Bainbridge Pediatrics'),
	('Theressa Trocchio, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Mason Collett, M.D.', 'Bainbridge Pediatrics'),
	('Tomi Politi, M.D.', 'Panhandle Plastic Surgery'),
	('Almeta Angelillo, M.D.', 'Moss Bay Wellness Center'),
	('Jeanette Mccade, M.D.', 'St Josephs Hospital And Med Center'),
	('Kelly Zisk, M.D.', 'St John's Clinic'),
	('Gia Edmund, M.D.', 'Healthfirst Sleep Center'),
	('Rosia Peroutka, M.D.', 'Wattles Park Family Practice'),
	('Mona Billa, M.D.', 'Heaton Williams & Benavides'),
	('Andrew Munari, M.D.', 'Silverdale Psychiatric'),
	('Giovanna Renova, M.D.', 'Panhandle Plastic Surgery'),
	('Ellis Kandarian, M.D.', 'Advantage Health Care'),
	('Pasquale Cryder, M.D.', 'Associated Colon & Rectal Srgn'),
	('Rosio Hussey, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Criselda Fagnoni, M.D.', 'F P Assoc'),
	('Nannie Cheverton, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Shante Masias, M.D.', 'Advantage Health Care'),
	('Augusta Begin, M.D.', 'Memorial NW Otolaryngology'),
	('Golden Hubbell, M.D.', 'Trusstek'),
	('Delphia Loesche, M.D.', 'Silverdale Psychiatric'),
	('Johnny Roeth, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Demarcus Epping, M.D.', 'Gadsden Orthopaedic Assoc'),
	('Matt Schlaht, M.D.', 'Northwest Occupational Medicine'),
	('Kris Fleurilus, M.D.', 'North Star Medical Center'),
	('Addie Cramer, M.D.', 'Charles C Young MD'),
	('Sun Killin, M.D.', 'Northwest Occupational Medicine'),
	('Sheena Granroth, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Libbie Metta, M.D.', 'Fusion Therapy LLC'),
	('Precious Godwin, M.D.', 'University Orthopedics Ctr'),
	('Asa Urenio, M.D.', 'St Louis Gynecology & Oncology'),
	('Clelia Freiberger, M.D.', 'Allergy & Asthma Care'),
	('Wilfred Zemke, M.D.', 'Piedmont Ear Nose-Throat Assoc'),
	('Orval Arguelles, M.D.', 'Healthfirst Sleep Center'),
	('Logan Brake, M.D.', 'Womans Digital Imaging'),
	('Rufus Cregeen, M.D.', 'Advantage Health Care'),
	('Dave Geneseo, M.D.', 'North Star Medical Center'),
	('Kasha Szalay, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Nancy Niel, M.D.', 'University Orthopedics Ctr'),
	('Cynthia Lablue, M.D.', 'Wattles Park Family Practice'),
	('Cristina Koczur, M.D.', 'North Star Medical Center'),
	('Saran Woolwine, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Tran Berstler, M.D.', 'Southcenter Cosmetic Surgery'),
	('Errol Viengxay, M.D.', 'Associated Colon & Rectal Srgn'),
	('Leda Gatrell, M.D.', 'Anoka Aeromedical Clinic'),
	('Bobby Castell, M.D.', 'University Orthopedics Ctr'),
	('Giuseppina Ronsini, M.D.', 'Temas Eye Ctr'),
	('Concha Godina, M.D.', 'Northwest Occupational Medicine'),
	('Leroy Etchinson, M.D.', 'Moss Bay Wellness Center'),
	('Mikki Cozzy, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Erma Mouse, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Latoria Cipriano, M.D.', 'Orthopedics Northwest Llp'),
	('Carter Friesen, M.D.', 'St John's Clinic'),
	('Tracee Nater, M.D.', 'Charles C Young MD'),
	('Trudi Plumlee, M.D.', 'Silverdale Psychiatric'),
	('Jacalyn Vreugdenhil, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Carline Severtson, M.D.', 'Charles C Young MD'),
	('Florrie Mccaine, M.D.', 'Southwest Dermatology'),
	('Myrtice Inman, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Valorie Rizal, M.D.', 'Bainbridge Pediatrics'),
	('Tamera Hellickson, M.D.', 'Panhandle Plastic Surgery'),
	('Rozanne Gumbert, M.D.', 'Hefner Pointe Youth OPT Pllc'),
	('Stacy Kennemer, M.D.', 'Randolph Internal Medicine'),
	('Bruce Servantes, M.D.', 'Northwest Asthma Allrgy Ctr PS'),
	('Sook Pistorius, M.D.', 'Memorial NW Otolaryngology'),
	('Yaeko Vesper, M.D.', 'Wattles Park Family Practice'),
	('Norine Gannetti, M.D.', 'Orthopedics Northwest Llp'),
	('Jeni Laselle, M.D.', 'Center For Psychotherapy'),
	('Claude Amaker, M.D.', 'University Orthopedics Ctr'),
	('Kasey Latch, M.D.', 'South Valley Inc'),
	('Henry Scholer, M.D.', 'Silverdale Psychiatric'),
	('Su Biebel, M.D.', 'Center For Psychotherapy'),
	('Delbert Pollman, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Andrea Subich, M.D.', 'Allergy & Asthma Care'),
	('Eulalia Mergist, M.D.', 'Northwest Occupational Medicine'),
	('Magdalena Loosle, M.D.', 'New Horizons'),
	('Charlsie Escarsega, M.D.', 'Flagstff Cmmnty Hosp AUX GFT'),
	('Onie Solar, M.D.', 'Fisher Investment Corporation'),
	('Donnette Cunningham, M.D.', 'Southcenter Cosmetic Surgery'),
	('Harold Kresge, M.D.', 'Nova Care');
