INSERT INTO insuranceCompany (`name`,`network`,`address$id`) VALUES
       ('Aetna','SW',882),
       ('BlueCross','MW',625),
       ('Anthem','SW',1718),
       ('Medicare','NW',424),
       ('Aflac','W',2312),
       ('GHP','W',568),
       ('Humana','SW',1521),
       ('Highmark','W',1295),
       ('CareFirst','SW',690),
       ('Premera','W',18),
       ('Centene','NE',840),
       ('UnitedHealthGroup','SE',2334),
       ('HCSC','SW',129),
       ('Cigna','MW',2040),
       ('Coventry','W',370);
