INSERT INTO specialist (`doctor$name`, `doctor$practiceName`, `specialty`) VALUES
	('Billie Poser, M.D.', 'Bainbridge Pediatrics','Psychiatry'),
	('Lyn Brigham, M.D.', 'Center For Genetic Testing At Saint','Dermatology'),
	('Pearlie Mcelhany, M.D.', 'Trusstek','Oncology'),
	('Eleanor Vegter, M.D.', 'Southwest Dermatology','Dermatology'),
	('Charla Joesph, M.D.', 'Moss Bay Wellness Center','Radiology'),
	('Karon Knittel, M.D.', 'Fisher Investment Corporation','Anesthesiology'),
	('Leontine Horka, M.D.', 'Northwest Occupational Medicine','Obstetrics'),
	('Slyvia Hulett, M.D.', 'Gadsden Orthopaedic Assoc','Geneology'),
	('Sharell Ayre, M.D.', 'Bainbridge Pediatrics','Dermatology'),
	('Vertie Placha, M.D.', 'North Star Medical Center','Oncology'),
	('Carline Carmany, M.D.', 'Center For Sight Inc','Anesthesiology'),
	('Woodrow Mccomis, M.D.', 'Advantage Health Care','Orthopaedics'),
	('Keitha Juart, M.D.', 'South Valley Inc','Psychiatry'),
	('Jennifer Perine, M.D.', 'Heaton Williams & Benavides','Pediatrics'),
	('Neda Wray, M.D.', 'Silverdale Psychiatric','Gastroenterology'),
	('Amberly Soos, M.D.', 'Temas Eye Ctr','Neurology'),
	('Yan Rocheleau, M.D.', 'Center For Psychotherapy','Geneology'),
	('Renee Scarlet, M.D.', 'New Horizons','Psychiatry'),
	('King Haacke, M.D.', 'North Star Medical Center','Dermatology'),
	('Roberto Maciejko, M.D.', 'South Valley Inc','Dermatology'),
	('Louann Watrs, M.D.', 'Womans Digital Imaging','Neurology'),
	('Grant Tall, M.D.', 'Heaton Williams & Benavides','Oncology'),
	('Enda Kanoff, M.D.', 'Piedmont Ear Nose-Throat Assoc','Psychiatry'),
	('Otha Waugaman, M.D.', 'Southwest Dermatology','Pediatrics'),
	('Kristina Klice, M.D.', 'Silverdale Psychiatric','Neurology'),
	('Virginia Boldery, M.D.', 'St John''s Clinic','Anesthesiology'),
	('Valene Shasky, M.D.', 'St Josephs Hospital And Med Center','Endocrinology'),
	('Glenn Polintan, M.D.', 'Bainbridge Pediatrics','Gastroenterology'),
	('Karol Zellman, M.D.', 'Heaton Williams & Benavides','Radiology'),
	('Georgine Rutiaga, M.D.', 'North Raleigh Pediatric Group','Radiology'),
	('Jae Laro, M.D.', 'Center For Health & Wellness','Neurology'),
	('Louie Prye, M.D.', 'St Josephs Hospital And Med Center','Endocrinology'),
	('Zola Arbizo, M.D.', 'Southwest Dermatology','Obstetrics'),
	('Elaine Valin, M.D.', 'St Josephs Hospital And Med Center','Pediatrics'),
	('Dallas Tate, M.D.', 'Heaton Williams & Benavides','Obstetrics'),
	('Aleisha Stroede, M.D.', 'St John''s Clinic','Orthopaedics'),
	('Despina Patsy, M.D.', 'Charles C Young MD','Obstetrics'),
	('Jospeh Lory, M.D.', 'Bainbridge Pediatrics','Radiology'),
	('Ronald Claridge, M.D.', 'University Orthopedics Ctr','Gastroenterology'),
	('Charles Bellomo, M.D.', 'Bainbridge Pediatrics','Dermatology'),
	('Lanny Annonio, M.D.', 'St John''s Clinic','Psychiatry'),
	('Burton Virag, M.D.', 'Moss Bay Wellness Center','Obstetrics'),
	('Norbert Fant, M.D.', 'Piedmont Ear Nose-Throat Assoc','Anesthesiology'),
	('Daine Noury, M.D.', 'Refractive Center Of Ohio','Radiology'),
	('Benedict Sotiriou, M.D.', 'Center For Genetic Testing At Saint','Geneology'),
	('Elenora Plock, M.D.', 'Randolph Internal Medicine','Eurology'),
	('Lakesha Freedland, M.D.', 'South Valley Inc','Dermatology'),
	('Ligia Huron, M.D.', 'St Louis Gynecology & Oncology','Cardiology'),
	('Elene Armacost, M.D.', 'New Horizons','Dermatology'),
	('Sau Zertuche, M.D.', 'Gadsden Orthopaedic Assoc','Endocrinology'),
	('Sau Cumberbatch, M.D.', 'Arizona Advanced Dermatology','Endocrinology'),
	('Criselda Carriedo, M.D.', 'Flagstff Cmmnty Hosp AUX GFT','Orthopaedics'),
	('Roy Williemae, M.D.', 'Trusstek','Geneology'),
	('Terrance Rudisell, M.D.', 'St John''s Clinic','Hematology'),
	('Kandice Valot, M.D.', 'Center For Genetic Testing At Saint','Dermatology'),
	('Melita Adwell, M.D.', 'Hague Ctr-Cosmetic & Plastic','Geneology'),
	('Manuela Abbate, M.D.', 'Associated Colon & Rectal Srgn','Psychiatry'),
	('Maryrose Surman, M.D.', 'Randolph Internal Medicine','Cardiology'),
	('Hershel Molleda, M.D.', 'St Josephs Hospital And Med Center','Neurology'),
	('Ruby Agricola, M.D.', 'Allergy Sleep & Lung Care','Hematology'),
	('Sheri Thibodaux, M.D.', 'Panhandle Plastic Surgery','Geneology'),
	('Fiona Wlodarczyk, M.D.', 'Gadsden Orthopaedic Assoc','Obstetrics'),
	('Isabelle Nievas, M.D.', 'Silverdale Psychiatric','Radiology'),
	('Latrina Mohn, M.D.', 'University Orthopedics Ctr','Pediatrics'),
	('Paz Paige, M.D.', 'Healthfirst Sleep Center','Cardiology'),
	('Gerald Korey, M.D.', 'University Orthopedics Ctr','Radiology'),
	('Veronica Mentgen, M.D.', 'Refractive Center Of Ohio','Hematology'),
	('Vickey Guilliams, M.D.', 'Piedmont Ear Nose-Throat Assoc','Orthopaedics'),
	('Latashia Ventresca, M.D.', 'Randolph Internal Medicine','Gastroenterology'),
	('Patrica Speelman, M.D.', 'St John''s Clinic','Gastroenterology'),
	('Torie Gallante, M.D.', 'Advantage Health Care','Obstetrics'),
	('Summer Dantoni, M.D.', 'Nova Care','Radiology'),
	('Rebbeca Opara, M.D.', 'Memorial NW Otolaryngology','Gastroenterology'),
	('Rosana Rupard, M.D.', 'Anoka Aeromedical Clinic','Eurology'),
	('Ethan Levett, M.D.', 'Northwest Asthma Allrgy Ctr PS','Psychiatry'),
	('Thanh Rehmert, M.D.', 'Allergy Sleep & Lung Care','Anesthesiology'),
	('Valrie Taulbee, M.D.', 'Heaton Williams & Benavides','Cardiology'),
	('Hilton Plumadore, M.D.', 'Temas Eye Ctr','Anesthesiology'),
	('Darlene Garibay, M.D.', 'Fisher Investment Corporation','Cardiology'),
	('Linh Keomanivong, M.D.', 'Orthopedics Northwest Llp','Pediatrics'),
	('Lynetta Sierer, M.D.', 'North Star Medical Center','Dermatology'),
	('Felicia Guo, M.D.', 'Refractive Center Of Ohio','Eurology'),
	('Nelson Krukowski, M.D.', 'Cascade Physicians','Endocrinology'),
	('Vicenta Smigiel, M.D.', 'University Orthopedics Ctr','Geneology'),
	('Rebeca Ahia, M.D.', 'Charles C Young MD','Eurology'),
	('Stephen Hunstiger, M.D.', 'Refractive Center Of Ohio','Pediatrics'),
	('Luisa Dehay, M.D.', 'Pediatric Place','Pediatrics'),
	('Julianne Broward, M.D.', 'Center For Genetic Testing At Saint','Geneology'),
	('Leatha Kacher, M.D.', 'Memorial NW Otolaryngology','Orthopaedics'),
	('Jeanette Mccade, M.D.', 'St Josephs Hospital And Med Center','Endocrinology'),
	('Ellis Kandarian, M.D.', 'Advantage Health Care','Hematology'),
	('Criselda Fagnoni, M.D.', 'F P Assoc','Cardiology'),
	('Kris Fleurilus, M.D.', 'North Star Medical Center','Endocrinology'),
	('Cristina Koczur, M.D.', 'North Star Medical Center','Cardiology'),
	('Erma Mouse, M.D.', 'Hefner Pointe Youth OPT Pllc','Anesthesiology'),
	('Florrie Mccaine, M.D.', 'Southwest Dermatology','Radiology'),
	('Sook Pistorius, M.D.', 'Memorial NW Otolaryngology','Psychiatry');

