INSERT INTO specialist (`name`, `practiceName`, `specialty`) VALUES
	('Billie Poser, M.D.', 'Bainbridge Pediatrics','{}'),
	('Lyn Brigham, M.D.', 'Center For Genetic Testing At Saint','{}'),
	('Pearlie Mcelhany, M.D.', 'Trusstek','{}'),
	('Eleanor Vegter, M.D.', 'Southwest Dermatology','{}'),
	('Charla Joesph, M.D.', 'Moss Bay Wellness Center','{}'),
	('Karon Knittel, M.D.', 'Fisher Investment Corporation','{}'),
	('Leontine Horka, M.D.', 'Northwest Occupational Medicine','{}'),
	('Slyvia Hulett, M.D.', 'Gadsden Orthopaedic Assoc','{}'),
	('Sharell Ayre, M.D.', 'Bainbridge Pediatrics','{}'),
	('Vertie Placha, M.D.', 'North Star Medical Center','{}'),
	('Carline Carmany, M.D.', 'Center For Sight Inc','{}'),
	('Woodrow Mccomis, M.D.', 'Advantage Health Care','{}'),
	('Keitha Juart, M.D.', 'South Valley Inc','{}'),
	('Jennifer Perine, M.D.', 'Heaton Williams & Benavides','{}'),
	('Neda Wray, M.D.', 'Silverdale Psychiatric','{}'),
	('Amberly Soos, M.D.', 'Temas Eye Ctr','{}'),
	('Yan Rocheleau, M.D.', 'Center For Psychotherapy','{}'),
	('Renee Scarlet, M.D.', 'New Horizons','{}'),
	('King Haacke, M.D.', 'North Star Medical Center','{}'),
	('Roberto Maciejko, M.D.', 'South Valley Inc','{}'),
	('Louann Watrs, M.D.', 'Womans Digital Imaging','{}'),
	('Grant Tall, M.D.', 'Heaton Williams & Benavides','{}'),
	('Enda Kanoff, M.D.', 'Piedmont Ear Nose-Throat Assoc','{}'),
	('Otha Waugaman, M.D.', 'Southwest Dermatology','{}'),
	('Kristina Klice, M.D.', 'Silverdale Psychiatric','{}'),
	('Virginia Boldery, M.D.', 'St John''s Clinic','{}'),
	('Valene Shasky, M.D.', 'St Josephs Hospital And Med Center','{}'),
	('Glenn Polintan, M.D.', 'Bainbridge Pediatrics','{}'),
	('Karol Zellman, M.D.', 'Heaton Williams & Benavides','{}'),
	('Georgine Rutiaga, M.D.', 'North Raleigh Pediatric Group','{}'),
	('Jae Laro, M.D.', 'Center For Health & Wellness','{}'),
	('Louie Prye, M.D.', 'St Josephs Hospital And Med Center','{}'),
	('Zola Arbizo, M.D.', 'Southwest Dermatology','{}'),
	('Elaine Valin, M.D.', 'St Josephs Hospital And Med Center','{}'),
	('Dallas Tate, M.D.', 'Heaton Williams & Benavides','{}'),
	('Aleisha Stroede, M.D.', 'St John''s Clinic','{}'),
	('Despina Patsy, M.D.', 'Charles C Young MD','{}'),
	('Jospeh Lory, M.D.', 'Bainbridge Pediatrics','{}'),
	('Ronald Claridge, M.D.', 'University Orthopedics Ctr','{}'),
	('Charles Bellomo, M.D.', 'Bainbridge Pediatrics','{}'),
	('Lanny Annonio, M.D.', 'St John''s Clinic','{}'),
	('Burton Virag, M.D.', 'Moss Bay Wellness Center','{}'),
	('Norbert Fant, M.D.', 'Piedmont Ear Nose-Throat Assoc','{}'),
	('Daine Noury, M.D.', 'Refractive Center Of Ohio','{}'),
	('Benedict Sotiriou, M.D.', 'Center For Genetic Testing At Saint','{}'),
	('Elenora Plock, M.D.', 'Randolph Internal Medicine','{}'),
	('Lakesha Freedland, M.D.', 'South Valley Inc','{}'),
	('Ligia Huron, M.D.', 'St Louis Gynecology & Oncology','{}'),
	('Elene Armacost, M.D.', 'New Horizons','{}'),
	('Sau Zertuche, M.D.', 'Gadsden Orthopaedic Assoc','{}'),
	('Sau Cumberbatch, M.D.', 'Arizona Advanced Dermatology','{}'),
	('Criselda Carriedo, M.D.', 'Flagstff Cmmnty Hosp AUX GFT','{}'),
	('Roy Williemae, M.D.', 'Trusstek','{}'),
	('Terrance Rudisell, M.D.', 'St John''s Clinic','{}'),
	('Kandice Valot, M.D.', 'Center For Genetic Testing At Saint','{}'),
	('Melita Adwell, M.D.', 'Hague Ctr-Cosmetic & Plastic','{}'),
	('Manuela Abbate, M.D.', 'Associated Colon & Rectal Srgn','{}'),
	('Maryrose Surman, M.D.', 'Randolph Internal Medicine','{}'),
	('Hershel Molleda, M.D.', 'St Josephs Hospital And Med Center','{}'),
	('Ruby Agricola, M.D.', 'Allergy Sleep & Lung Care','{}'),
	('Sheri Thibodaux, M.D.', 'Panhandle Plastic Surgery','{}'),
	('Fiona Wlodarczyk, M.D.', 'Gadsden Orthopaedic Assoc','{}'),
	('Isabelle Nievas, M.D.', 'Silverdale Psychiatric','{}'),
	('Latrina Mohn, M.D.', 'University Orthopedics Ctr','{}'),
	('Paz Paige, M.D.', 'Healthfirst Sleep Center','{}'),
	('Gerald Korey, M.D.', 'University Orthopedics Ctr','{}'),
	('Veronica Mentgen, M.D.', 'Refractive Center Of Ohio','{}'),
	('Vickey Guilliams, M.D.', 'Piedmont Ear Nose-Throat Assoc','{}'),
	('Latashia Ventresca, M.D.', 'Randolph Internal Medicine','{}'),
	('Patrica Speelman, M.D.', 'St John''s Clinic','{}'),
	('Torie Gallante, M.D.', 'Advantage Health Care','{}'),
	('Summer Dantoni, M.D.', 'Nova Care','{}'),
	('Rebbeca Opara, M.D.', 'Memorial NW Otolaryngology','{}'),
	('Rosana Rupard, M.D.', 'Anoka Aeromedical Clinic','{}'),
	('Ethan Levett, M.D.', 'Northwest Asthma Allrgy Ctr PS','{}'),
	('Thanh Rehmert, M.D.', 'Allergy Sleep & Lung Care','{}'),
	('Valrie Taulbee, M.D.', 'Heaton Williams & Benavides','{}'),
	('Hilton Plumadore, M.D.', 'Temas Eye Ctr','{}'),
	('Darlene Garibay, M.D.', 'Fisher Investment Corporation','{}'),
	('Linh Keomanivong, M.D.', 'Orthopedics Northwest Llp','{}'),
	('Lynetta Sierer, M.D.', 'North Star Medical Center','{}'),
	('Felicia Guo, M.D.', 'Refractive Center Of Ohio','{}'),
	('Nelson Krukowski, M.D.', 'Cascade Physicians','{}'),
	('Vicenta Smigiel, M.D.', 'University Orthopedics Ctr','{}'),
	('Rebeca Ahia, M.D.', 'Charles C Young MD','{}'),
	('Stephen Hunstiger, M.D.', 'Refractive Center Of Ohio','{}'),
	('Luisa Dehay, M.D.', 'Pediatric Place','{}'),
	('Julianne Broward, M.D.', 'Center For Genetic Testing At Saint','{}'),
	('Leatha Kacher, M.D.', 'Memorial NW Otolaryngology','{}'),
	('Jeanette Mccade, M.D.', 'St Josephs Hospital And Med Center','{}'),
	('Ellis Kandarian, M.D.', 'Advantage Health Care','{}'),
	('Criselda Fagnoni, M.D.', 'F P Assoc','{}'),
	('Kris Fleurilus, M.D.', 'North Star Medical Center','{}'),
	('Cristina Koczur, M.D.', 'North Star Medical Center','{}'),
	('Erma Mouse, M.D.', 'Hefner Pointe Youth OPT Pllc','{}'),
	('Florrie Mccaine, M.D.', 'Southwest Dermatology','{}'),
	('Sook Pistorius, M.D.', 'Memorial NW Otolaryngology','{}');
