INSERT INTO phlebotomist (`name`, `clinic`) VALUES
('Calandra Bohrman', 'Highlands Medical Center'),
('Carmelina Morisky', 'Parkview Regional Medical Center'),
('Nettie Lawalin', 'St Francis Medical Center'),
('Ashton Yoshimori', 'Abbeville Area Medical Center'),
('Murray Marn', 'St Marys Regional Medical Center'),
('Nelia Veldhuizen', 'Miners\' Colfax Medical Center'),
('Bernadine Aunkst', 'Cape Regional Medical Center Inc'),
('Rossana Crespi', 'Atoka County Medical Center'),
('Lisette Drop', 'Stevens Community Medical Center'),
('Hollis Helmink', 'Pella Regional Health Center'),
('Burma Fritchman', 'Sandhills Regional Medical Center'),
('Suanne Hartinger', 'Eastern Maine Medical Center'),
('Laurette Orbaker', 'Baptist Medical Center East'),
('Leila Doughtery', 'Alliancehealth Seminole'),
('Natisha Kaufusi', 'Mile Bluff Medical Center'),
('Rochelle Mcaboy', 'Spectrum Health Pennock'),
('Lulu Papageorge', 'Sakakawea Medical Center - Cah'),
('Bethanie Kashan', 'Advocate Bromenn Medical Center'),
('Ardelle Thornton', 'Aria Health'),
('Tamara Siert', 'Lifecare Medical Center'),
('Velvet Wolfer', 'Healthsource Saginaw'),
('Fernando Mccally', 'Platte Valley Medical Center'),
('Clemmie Desjardiws', 'Carolinas Healthcare System Pineville'),
('Daysi Carbal', 'Dale Medical Center'),
('Chauncey Magil', 'Riverside Regional Medical Center'),
('Wynell Paluch', 'Our Lady Of Lourdes Medical Center'),
('Ciera Naveed', 'Sgmc Berrien Campus'),
('Amos Friebel', 'Davie Medical Center'),
('Lorri Vondielingen', 'Westchester Medical Center'),
('Lucia Kizzie', 'Tanner Medical Center - Carrollton'),
('Julissa Dorson', 'Saint Francis Medical Center'),
('Lucila Consolo', 'Quartz Mountain Medical Center'),
('Alesia Wedgewood', 'Genesis Health System'),
('Aron Clan', 'Denton Regional Medical Center'),
('Heike Hill', 'Memorial Healthcare System'),
('Noel Heaney', 'Los Alamos Medical Center'),
('Chi Bobseine', 'Atrium Medical Center'),
('Warner Abbate', 'Redmond Regional Medical Center'),
('Mayme Haus', 'Hima San Pablo Bayamon'),
('Connie Vineyard', 'Rmc Jacksonville'),
('Aurelia Woolem', 'Stillwater Medical Center Authority'),
('Danial Yagoudaef', 'San Juan Regional Medical Center'),
('Ladawn Revolorio', 'Baptist Health La Grange'),
('Verlene Budzik', 'Riceland Medical Center'),
('Dayle Leneave', 'Zuni Comprehensive Community Health Center'),
('Broderick Grano', 'Children\'s Home Of Pittsburgh'),
('Jennifer Kludt', 'Avera St Benedict Health Center - Cah'),
('Tiny Orrell', 'De Queen Medical Center'),
('Natalya Staines', 'Franciscan Health Crawfordsville'),
('Teri Archilla', 'Lea Regional Medical Center'),
('Nila Ziegenhagen', 'St Francis Health Center Inc'),
('Adell Henderlight', 'Jackson Medical Center'),
('Deonna Dewey', 'Johnston Health'),
('Catharine Yant', 'Liberty Regional Medical Center'),
('Suanne Magan', 'Magnolia Regional Health Center'),
('Melda Knopf', 'Osf Saint Anthony\'s Health Center'),
('Cruz Codey', 'Muscogee (creek) Nation Medical Center'),
('Beryl Kitchell', 'Deer River Healthcare Center'),
('Larissa Ossenfort', 'Rose Medical Center'),
('Jonnie Hongisto', 'Lakeview Medical Center'),
('Chang Severs', 'Medstar Montgomery Medical Center'),
('Monroe Rosetti', 'Greater Regional Medical Center'),
('Ashlyn Overhulser', 'Healthsource Saginaw'),
('Alysha Nelligan', 'Mountrail County Medical Center'),
('Nakia Wamboldt', 'Terrebonne General Medical Center'),
('Shella Schuller', 'Sutter Roseville Medical Center'),
('Ezekiel Silliman', 'Parrish Medical Center'),
('Marcene Palmour', 'Touro Infirmary'),
('Lester Richberg', 'Cortland Regional Medical Center'),
('Gina Ashworth', 'United Memorial Medical Center'),
('Rocky Standefer', 'Aiken Regional Medical Center'),
('Bob Gates', 'Mayo Clinic Health System in Red Wing'),
('Tyson Arosemena', 'Southwest Healthcare System'),
('Paulene Asberry', 'Graham Regional Medical Center'),
('Margert Ovington', 'Lawrence Medical Center'),
('Lourie Teas', 'Margaret Mary Health'),
('Pearly Wrighton', 'Greenfield Area Medical Center'),
('Rena Graeff', 'Choctaw Health Center'),
('In Liscio', 'Carolinas Med Ctr-university'),
('Althea Shidemantle', 'St Vincent\'s Medical Center Riverside'),
('Gracie Woolfolk', 'Adventist Glenoaks'),
('Zella Mcgaughan', 'Physicians Medical Center'),
('Eden Monnier', 'Albert Einstein Medical Center'),
('Golden Andon', 'St Anthony North Health Campus'),
('Lesia Gearhart', 'Thedacare Medical Center New London'),
('Alaina Brunker', 'Burleson St Joseph Health Center'),
('Erin Ankersen', 'Christus Coushatta Health Care Center'),
('Michiko Salvietti', 'Chi St Vincent Morrilton'),
('Jorge Chambliss', 'St Francis Medical Center'),
('Milly Eisenhart', 'St Charles - Madras'),
('Tambra Basua', 'Twin Lakes Regional Medical Center'),
('Quincy Parmer', 'St Anthony\'s Medical Center'),
('Dominique Samiec', 'Advocate Bromenn Medical Center'),
('An Bowerize', 'Cleveland Clinic'),
('Maddie Fernendez', 'Swedish Medical Center'),
('Margit Lamora', 'Mercy Medical Center'),
('Shawnda Sydnes', 'University Of Md Medical Center Midtown Campus'),
('Katharina Pucker', 'Kadlec Regional Medical Center'),
('Rossana Kacvinsky', 'Carilion New River Valley Medical Center'),
('Divina Campagna', 'Medical Center South Arkansas');
